export const HANDLE_PASSWORD_CHANGE = 'HANDLE_PASSWORD_CHANGE';
export const START_PASSWORD_PROMPT = 'START_PASSWORD_PROMPT';
export const PASSWORD_PROMPT_SUCCESS = 'PASSWORD_PROMPT_SUCCESS';
export const PASSWORD_PROMPT_FAILURE = 'PASSWORD_PROMPT_FAILURE';
