// main.js, the entry point of the app, handles starting up the app window. It
// runs index.html which maps all other classes.

// Global variables and require statements available to all main processes
'use strict';
var app = require('app');
var path = require('path');
var BrowserWindow = require('browser-window');
var Tray = require('tray');
var fs = require("fs");
var daemon = require("./js/daemonManager")
// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the javascript object is GCed.
var mainWindow;

// startMainWindow creates the first window and loads and index.html.
function startMainWindow() {
	// Open the UI with full screen size. 'screen' can only be required after
	// app.on('ready') 
	var atomScreen = require('screen');
	var size = atomScreen.getPrimaryDisplay().workAreaSize;

	// Give tray/taskbar icon path
	var iconPath = path.join(__dirname,'dependencies', 'images', 'sia.png');
	var appIcon = new Tray(iconPath);
	appIcon.setToolTip('A highly efficient decentralized storage network.');

	// Create the browser
	mainWindow = new BrowserWindow({
		'width': size.width,
		'height': size.height,
		'use-content-size': true,
		'icon': iconPath,
		'title': 'Sia'
	});

	// Choose not to show the menubar
	mainWindow.setMenuBarVisibility(false);
	
	// Load the index.html of the app.
	mainWindow.loadUrl('file://' + __dirname + '/index.html');

	// Focus selector on test-ui	
	mainWindow.focus();

	// DEVTOOL: Open the devtools.
	//mainWindow.openDevTools();

	// Emitted when the window is closed.
	mainWindow.on('closed', function() {
		// Dereference the window object so that the GC cleans up.
		mainWindow = null;
	});
}

// find a config file if one exists. Otherwise, make default
function loadConfig(callback) {
    // TODO: More error handling
    var configPath = path.join(__dirname, "config.json");
	fs.readFile(configPath, function(err, data) {
		if (err) {
			// default config
			callback({
				"autogenerated": true,
				"siad_cmd": process.platform == 'win32' ? "./siad.exe" : "./siad",
				"siad_addr": "http://localhost:9980"
			});
		} else {
			// config found in filespace
			callback(data);
		}
	});
}

// Quit when all windows are closed.
app.on('window-all-closed', function() {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

// When Electron loading has finished, start the daemon then the UI
app.on('ready', function() {
	loadConfig(function(config) {
		daemon.start(config, function(err) {
			if (!err) {
				startMainWindow();
			} else {
				alert(err);
			}
		});
	});
});
